apiVersion: v1
kind: Pod
metadata:
  name: kube-proxy
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-proxy
    image: {{ k8s_hyperkube_image }}:{{ k8s_hyperkube_image_tag }}
    command:
    - /hyperkube
    - proxy
    - --master={{ k8s_url_scheme }}://{% if inventory_hostname in k8s_master_hosts %}127.0.0.1{% else %}{{ k8s_master_hosts[0] }}{% endif %}:{{ k8s_api_port }}
    - --kubeconfig={{ k8s_policy_dir }}/kube-proxy.kubeconfig
    - --v={{ k8s_log_level }}
    securityContext:
      privileged: true
    volumeMounts:
    - name: policy
      mountPath: {{ k8s_policy_dir }}
      readOnly: true
    - name: certificates
      mountPath: {{ ssl_dir }}
      readOnly: true
  volumes:
  - name: policy
    hostPath:
      path: {{ k8s_policy_dir }}
  - name: certificates
    hostPath:
      path: {{ ssl_dir }}
