{% raw %}
    #
    # Service alerts (from blackbox-exporter)
    #
    - name: service-alerts
      rules:

      #
      # Alert on service is unreachable > 5 min
      #
      - alert: ServiceIsUnreachable
        expr: probe_success{job="kubernetes-services"} == 0 or absent(probe_success{job="kubernetes-services"} == 1)
        for: 5m
        labels:
          severity: warning
          notify: sre
        annotations:
          description: "{{ $labels.kubernetes_namespace }}/{{ $labels.kubernetes_service_name }}: Service is unreachable"
          summary: "{{ $labels.kubernetes_namespace }}/{{ $labels.kubernetes_service_name }}: Service is unreachable more than 5 minutes"

{% endraw %}
