---

apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/probe: pushgateway
  labels:
    app: prometheus
    component: "pushgateway"
  namespace: {{ k8s_prometheus_namespace }}
  name: prometheus-pushgateway
spec:
  ports:
    - name: http
      port: 9091
      protocol: TCP
      targetPort: 9091
  selector:
    app: prometheus
    component: "pushgateway"
  type: "ClusterIP"

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: prometheus
    component: "pushgateway"
  namespace: {{ k8s_prometheus_namespace }}
  name: prometheus-pushgateway
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus
        component: "pushgateway"
    spec:
      containers:
        - name: prometheus-pushgateway
          image: "{{ k8s_prometheus_pushgateway_image }}:{{ k8s_prometheus_pushgateway_image_tag }}"
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 9091
          readinessProbe:
            httpGet:
              path: /#/status
              port: 9091
            initialDelaySeconds: 10
            timeoutSeconds: 10
          resources:
            limits:
              cpu: 10m
              memory: 32Mi
            requests:
              cpu: 10m
              memory: 32Mi

{% if k8s_prometheus_pushgateway_name is defined and k8s_prometheus_pushgateway_name != '' %}
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
    app: prometheus
    component: "pushgateway"
  namespace: {{ k8s_prometheus_namespace }}
  name: prometheus-pushgateway
spec:
  rules:
    - host: {{ k8s_prometheus_pushgateway_name }}
      http:
        paths:
          - backend:
              serviceName: prometheus-pushgateway
              servicePort: 9091
  tls:
    - hosts:
      - {{ k8s_prometheus_pushgateway_name }}
      secretName: tls-secret

{% endif %}
